import crypto from 'node:crypto';
import { config } from './config.js';

/**
 * Scripts the real Sinch ID (Auth0) login chain server-side: identifier -> password ->
 * (SMS OTP if challenged) -> CCP callback -> dashboard session cookie. Every hop's shape (URLs,
 * form field names, redirect targets) was captured byte-for-byte from a real browser HAR.
 *
 * This talks to id.sinch.com (Auth0) and auth.cd.api.sinch.com (the CCP backend) directly — a
 * different protocol concern from dashboard.ts's GraphQL/REST business client, hence its own file.
 * The resulting cookie is used exactly like a pasted one everywhere downstream (refreshCcpToken,
 * listAccounts, listProjects, ensureFreshAccessKey — all unchanged).
 *
 * KNOWN LIMITATION (confirmed live, do not re-investigate): the Sinch ID tenant's identifier page
 * embeds a Cloudflare Turnstile captcha via Auth0's native `auth0_v2` integration
 * (`data-captcha-provider="auth0_v2"`), with a hidden `<input name="captcha">` that only a real
 * browser's JS can populate with a valid token. A plain HTTP client has no JS engine/DOM for
 * Turnstile to challenge, so the identifier POST is rejected (`HTTP 400`, same page re-rendered)
 * before password or OTP are ever reached. This is a hard stop for THIS tenant, not a fixable
 * header/field/cookie bug — `hasCaptcha()` below detects it and fails fast with a clear message
 * instead of a confusing generic diagnostic. `LOGIN_MODE=dashboard` (paste a session cookie
 * obtained from a real browser login) is the working path when this triggers.
 */

const AUTH0_BASE = 'https://id.sinch.com';
const AUTH0_CLIENT_ID = 'SLIU20XWtmz9uQkXpUP17EKMBSxSNMwZ'; // dashboard SPA's public Auth0 client id — not a secret
const CCP_CALLBACK = 'https://auth.cd.api.sinch.com/login/oauth2/code/auth0';

// Client-capability flags Auth0's own JS injects into the login forms. Static values are fine —
// they only affect which auth *options* are offered (e.g. passkeys), not whether login succeeds.
const BROWSER_FLAGS = {
  'js-available': 'true',
  'webauthn-available': 'true',
  'is-brave': 'false',
  'webauthn-platform-available': 'true',
};

// A bare Node fetch sends none of these; Auth0 rejects requests missing them (a lightweight
// bot/CSRF check), so every hop mimics a real browser navigation.
const BROWSER_HEADERS = {
  'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36',
  Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8',
};

export class ScriptedLoginError extends Error {
  constructor(step: string, detail: string) {
    super(`scripted login failed at "${step}": ${detail}`);
  }
}

type CookieJar = Map<string, string>;

function jarFromHeader(header: string): CookieJar {
  const jar: CookieJar = new Map();
  for (const pair of header.split(';')) {
    const idx = pair.indexOf('=');
    if (idx > 0) jar.set(pair.slice(0, idx).trim(), pair.slice(idx + 1).trim());
  }
  return jar;
}

function mergeCookies(jar: CookieJar, res: Response): void {
  for (const setCookie of res.headers.getSetCookie()) {
    const [pair] = setCookie.split(';');
    const idx = pair.indexOf('=');
    if (idx > 0) jar.set(pair.slice(0, idx).trim(), pair.slice(idx + 1).trim());
  }
}

function cookieHeader(jar: CookieJar): string {
  return [...jar.entries()].map(([k, v]) => `${k}=${v}`).join('; ');
}

/**
 * One hop: fetch with browser-like headers + the jar's cookies attached, merge any new
 * Set-Cookie, never auto-follow. `referer` is the page the "browser" is navigating from —
 * Auth0 checks Origin/Referer on POSTs, so it's required on every form submission.
 */
async function hop(jar: CookieJar, url: string, referer?: string, init?: RequestInit): Promise<Response> {
  const res = await fetch(url, {
    ...init,
    redirect: 'manual',
    headers: {
      ...BROWSER_HEADERS,
      ...(referer ? { Referer: referer, Origin: new URL(referer).origin } : {}),
      ...(init?.headers ?? {}),
      Cookie: cookieHeader(jar),
    },
  });
  mergeCookies(jar, res);
  return res;
}

/** Resolve a Location header (absolute or relative-to-Auth0) into an absolute URL. */
function resolveLocation(location: string): string {
  return location.startsWith('http') ? location : new URL(location, AUTH0_BASE).toString();
}

/**
 * True if the page embeds Auth0's native Cloudflare Turnstile captcha widget — confirmed present
 * on this tenant's identifier page (see the module doc comment). A script cannot solve this: no
 * amount of header/field tuning produces a valid token, since Turnstile's token is generated by
 * real browser-environment checks (canvas/WebGL fingerprint, timing, TLS characteristics) that a
 * plain HTTP client has nothing to run. Treat this as a permanent stop, not a bug to keep chasing.
 */
function hasCaptcha(body: string): boolean {
  return body.includes('data-captcha-provider') || body.includes('ulp-captcha-container');
}

const CAPTCHA_BLOCKED_MESSAGE =
  'this Sinch ID tenant requires solving a CAPTCHA (Cloudflare Turnstile) on login, which cannot ' +
  'be completed by a script — there is no browser JS environment to solve the challenge. Use ' +
  'LOGIN_MODE=dashboard (paste a session cookie from a real browser login) instead.';

/**
 * Summarizes an unexpected response for diagnosis: status, the headers that distinguish a
 * Cloudflare block/challenge from an Auth0 application error, and a short body snippet. No user
 * PII is at risk here — this is what THEY sent back to a rejected request, not our own data.
 */
function diagnose(res: Response, body: string): string {
  const cf = ['server', 'cf-ray', 'cf-mitigated', 'content-type']
    .map((h) => [h, res.headers.get(h)])
    .filter(([, v]) => v)
    .map(([h, v]) => `${h}=${v}`)
    .join(' ');
  // Auth0's own error pages usually carry the real message in <title>, a visible heading, or a
  // JSON "description"/"error" field embedded in an inline script — pull those out specifically
  // rather than relying on a short raw snippet that likely lands in <head> boilerplate.
  const title = body.match(/<title>([^<]*)<\/title>/i)?.[1];
  const heading = body.match(/<h1[^>]*>([^<]*)<\/h1>/i)?.[1];
  const jsonError =
    body.match(/"description"\s*:\s*"([^"]{1,200})"/)?.[1] ??
    body.match(/"error(?:_description)?"\s*:\s*"([^"]{1,200})"/i)?.[1];
  const bodyTagIdx = body.search(/<body[^>]*>/i);
  const bodySnippet = bodyTagIdx >= 0 ? body.slice(bodyTagIdx, bodyTagIdx + 500) : body.slice(0, 500);

  const bits = [
    cf,
    title ? `title="${title}"` : null,
    heading ? `h1="${heading}"` : null,
    jsonError ? `error="${jsonError}"` : null,
    `bodyLen=${body.length}`,
    `bodyFromTag="${bodySnippet.replace(/\s+/g, ' ')}"`,
  ].filter(Boolean);
  return bits.join(' ');
}

async function requireRedirect(step: string, res: Response): Promise<string> {
  if (res.status !== 302 && res.status !== 303) {
    const body = await res.text().catch(() => '');
    if (hasCaptcha(body)) throw new ScriptedLoginError(step, CAPTCHA_BLOCKED_MESSAGE);
    throw new ScriptedLoginError(step, `expected a redirect, got HTTP ${res.status} (${diagnose(res, body)})`);
  }
  const location = res.headers.get('location');
  if (!location) throw new ScriptedLoginError(step, 'redirect had no Location header');
  return resolveLocation(location);
}

async function requireOk(step: string, res: Response): Promise<void> {
  if (!res.ok) {
    const body = await res.text().catch(() => '');
    if (hasCaptcha(body)) throw new ScriptedLoginError(step, CAPTCHA_BLOCKED_MESSAGE);
    throw new ScriptedLoginError(step, `HTTP ${res.status} (${diagnose(res, body)})`);
  }
}

export type ScriptedLoginResult =
  | { done: true; cookie: string }
  | { done: false; mfa: { cookieJar: string; mfaUrl: string } };

/**
 * Steps 1-4 (+5 if MFA is challenged): authorize -> identifier -> password -> resume ->
 * [mfa challenge]. Mirrors the exact request sequence a real browser makes (including the
 * intermediate page GETs) to stay indistinguishable from normal traffic.
 */
export async function scriptedLoginStep1(email: string, password: string): Promise<ScriptedLoginResult> {
  if (config.dashboardMock) {
    if (password === 'wrong') throw new ScriptedLoginError('password', 'invalid email or password');
    if (email.includes('nomfa')) return { done: true, cookie: 'mock-session-cookie' };
    return { done: false, mfa: { cookieJar: 'mock-jar', mfaUrl: 'mock://mfa-sms-challenge?state=mock' } };
  }

  const jar: CookieJar = new Map();

  // 1. Kick off the Auth0 authorization_code flow with the dashboard SPA's public client id.
  const outerState = crypto.randomBytes(24).toString('base64url');
  const nonce = crypto.randomBytes(16).toString('base64url');
  const authorizeUrl =
    `${AUTH0_BASE}/authorize?response_type=code&client_id=${AUTH0_CLIENT_ID}` +
    `&scope=${encodeURIComponent('openid profile email')}&redirect_uri=${encodeURIComponent(CCP_CALLBACK)}` +
    `&state=${outerState}&nonce=${nonce}`;
  let res = await hop(jar, authorizeUrl);
  const identifierUrl = await requireRedirect('authorize', res);

  // Auth0's own opaque transaction state, carried through every subsequent hop.
  const txnState = new URL(identifierUrl).searchParams.get('state');
  if (!txnState) throw new ScriptedLoginError('authorize', 'no transaction state in redirect');

  // 2. Load the identifier page (as a browser would), then submit the email.
  await requireOk('identifier-page', await hop(jar, identifierUrl, authorizeUrl));
  res = await hop(jar, identifierUrl, identifierUrl, {
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    body: new URLSearchParams({ state: txnState, username: email, 'allow-passkeys': 'true', ...BROWSER_FLAGS }),
  });
  const passwordUrl = await requireRedirect('identifier', res);

  // 3. Load the password page, then submit the password (same transaction state). A genuine
  // wrong-password re-renders this page (200) rather than redirecting — requireRedirect's
  // diagnostics distinguish that from a network/bot-detection block.
  await requireOk('password-page', await hop(jar, passwordUrl, identifierUrl));
  res = await hop(jar, passwordUrl, passwordUrl, {
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    body: new URLSearchParams({ state: txnState, username: email, password, ...BROWSER_FLAGS }),
  });
  const resumeUrl = await requireRedirect('password', res);

  // 4. Follow the resume redirect -> either an MFA challenge, or straight to the CCP callback.
  res = await hop(jar, resumeUrl, passwordUrl);
  const afterResume = await requireRedirect('resume', res);

  if (afterResume.includes('/u/mfa-sms-challenge')) {
    // 5. Loading the challenge page is what triggers Auth0 to actually send the SMS.
    await requireOk('mfa-challenge', await hop(jar, afterResume, resumeUrl));
    return { done: false, mfa: { cookieJar: cookieHeader(jar), mfaUrl: afterResume } };
  }

  return { done: true, cookie: await followToCallback(jar, afterResume, resumeUrl) };
}

/** Steps 6-8: submit the SMS code, follow through to the CCP callback, return the session cookie. */
export async function scriptedLoginSubmitOtp(
  mfa: { cookieJar: string; mfaUrl: string },
  code: string,
): Promise<string> {
  if (config.dashboardMock) {
    if (code === '000000') throw new ScriptedLoginError('otp', 'invalid code');
    return 'mock-session-cookie';
  }

  const jar = jarFromHeader(mfa.cookieJar);

  const mfaState = new URL(mfa.mfaUrl).searchParams.get('state');
  if (!mfaState) throw new ScriptedLoginError('otp', 'missing mfa state');

  const res = await hop(jar, mfa.mfaUrl, mfa.mfaUrl, {
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    body: new URLSearchParams({ state: mfaState, code, rememberBrowser: 'true' }),
  });
  const next = await requireRedirect('otp', res);
  return followToCallback(jar, next, mfa.mfaUrl);
}

/**
 * Follows any remaining /authorize/resume hop(s) until reaching the CCP callback host, then
 * fetches it — its response is the one that sets the dashboard session cookie.
 */
async function followToCallback(jar: CookieJar, url: string, referer: string): Promise<string> {
  let next = url;
  let ref = referer;
  for (let i = 0; i < 3 && !next.startsWith(CCP_CALLBACK); i++) {
    const res = await hop(jar, next, ref);
    ref = next;
    next = await requireRedirect('resume-chain', res);
  }
  const res = await hop(jar, next, ref);
  if (res.status !== 302 && res.status !== 303) {
    const body = await res.text().catch(() => '');
    if (hasCaptcha(body)) throw new ScriptedLoginError('ccp-callback', CAPTCHA_BLOCKED_MESSAGE);
    throw new ScriptedLoginError('ccp-callback', `HTTP ${res.status} (${diagnose(res, body)})`);
  }
  return cookieHeader(jar);
}
