import { readFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { registerAppResource, RESOURCE_MIME_TYPE } from '@modelcontextprotocol/ext-apps/server';

/**
 * MCP Apps preview for generate-rcs-message: an interactive phone-mockup that renders the
 * generated RCS template. Only relevant on hosts that implement the MCP Apps extension
 * (Claude/Codex desktop); other hosts (e.g. Gemini Enterprise) ignore it and use the
 * tool's text result.
 */

// Bump the version suffix whenever the preview HTML changes — hosts cache app resources by URI.
export const RCS_PREVIEW_URI = 'ui://sinch/rcs-preview-v2.html';

// In prod, import.meta.url resolves to dist/rcsPreview.js so the ui folder is at dist/ui/.
// In dev (tsx), it resolves to src/rcsPreview.ts so the ui folder is one level up at ui/.
const _base = dirname(fileURLToPath(import.meta.url));
const PREVIEW_PATH = existsSync(join(_base, 'ui', 'rcs-preview.html'))
  ? join(_base, 'ui', 'rcs-preview.html')
  : join(_base, '..', 'ui', 'rcs-preview.html');

export function registerRcsPreviewResource(server: McpServer): void {
  registerAppResource(
    server,
    'RCS Message Preview',
    RCS_PREVIEW_URI,
    { description: 'Interactive phone-mockup preview of an RCS message generated by generate-rcs-message.' },
    async () => {
      const html = await readFile(PREVIEW_PATH, 'utf-8');
      return {
        contents: [
          {
            uri: RCS_PREVIEW_URI,
            mimeType: RESOURCE_MIME_TYPE,
            text: html,
            _meta: {
              ui: {
                preferredFrameSize: { width: 420, height: 720 },
                // RCG card images are served from runware.ai; allowlist so <img>/<video> render
                // under the app's strict default CSP.
                csp: { resourceDomains: ['https://*.runware.ai'] },
              },
            },
          },
        ],
      };
    },
  );
}
