import { readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { registerAppResource, RESOURCE_MIME_TYPE } from '@modelcontextprotocol/ext-apps/server';

/**
 * MCP Apps preview for generate-rcs-message: an interactive phone-mockup that renders the
 * generated RCS template. Only relevant on hosts that implement the MCP Apps extension
 * (Claude/Codex desktop); other hosts (e.g. Gemini Enterprise) ignore it and use the
 * tool's text result.
 */

// Bump the version suffix whenever the preview HTML changes — hosts cache app resources by URI.
export const RCS_PREVIEW_URI = 'ui://sinch/rcs-preview-v2.html';

// Resolves to mcp-server/ui under tsx (dev) and dist/ui in prod (the build copies ui -> dist/ui).
const PREVIEW_PATH = join(dirname(fileURLToPath(import.meta.url)), '..', 'ui', 'rcs-preview.html');

export function registerRcsPreviewResource(server: McpServer): void {
  registerAppResource(
    server,
    'RCS Message Preview',
    RCS_PREVIEW_URI,
    { description: 'Interactive phone-mockup preview of an RCS message generated by generate-rcs-message.' },
    async () => {
      const html = await readFile(PREVIEW_PATH, 'utf-8');
      return {
        contents: [
          {
            uri: RCS_PREVIEW_URI,
            mimeType: RESOURCE_MIME_TYPE,
            text: html,
            _meta: {
              ui: {
                preferredFrameSize: { width: 420, height: 720 },
                // RCG card images are served from runware.ai; allowlist so <img>/<video> render
                // under the app's strict default CSP.
                csp: { resourceDomains: ['https://*.runware.ai'] },
              },
            },
          },
        ],
      };
    },
  );
}
